In [4]:
import polars as pl
import pickle


In [9]:
model_1 = '/root/lio/Trade_LOB_MultiModal/checkpoints/multi_modal_model_1/multi_modal_model_1_history.pkl'
model_2 = '/root/lio/Trade_LOB_MultiModal/checkpoints/multi_modal_model_2/multi_modal_model_2_history.pkl'
with open(model_1, 'rb') as f:
    history1 = pickle.load(f)

with open(model_2, 'rb') as f:
    history2 = pickle.load(f)



In [10]:
history1['best_val_metrics']

{'accuracy': 0.759384590232056,
 'precision_Down': np.float64(0.400086692674469),
 'recall_Down': np.float64(0.02712153267512929),
 'f1_Down': np.float64(0.050799416604749716),
 'support_Down': np.int64(34032),
 'precision_Stationary': np.float64(0.7655393890369572),
 'recall_Stationary': np.float64(0.9938963090621858),
 'f1_Stationary': np.float64(0.8648986422494176),
 'support_Stationary': np.int64(222816),
 'precision_Up': np.float64(0.28478802992518704),
 'recall_Up': np.float64(0.015539529187644577),
 'f1_Up': np.float64(0.029470967741935482),
 'support_Up': np.int64(36745),
 'precision_macro': 0.48347137054553774,
 'recall_macro': 0.3455191236416532,
 'f1_macro': 0.31505634219870093,
 'precision_weighted': 0.6630086922793021,
 'recall_weighted': 0.759384590232056,
 'f1_weighted': 0.6659728683143551,
 'precision_updown': np.float64(0.34243736129982805),
 'recall_updown': np.float64(0.021330530931386933),
 'f1_updown': np.float64(0.0401595131580539),
 'directional_accuracy': 0.0211

In [17]:
history2['train_history'][0]['val_metrics']

{'accuracy': 0.7580732510652501,
 'precision_Down': np.float64(0.34413087934560327),
 'recall_Down': np.float64(0.1236189468735308),
 'f1_Down': np.float64(0.18189679399874614),
 'support_Down': np.int64(34032),
 'precision_Stationary': np.float64(0.7760576044809804),
 'recall_Stationary': np.float64(0.979987972138446),
 'f1_Stationary': np.float64(0.8661815253588478),
 'support_Stationary': np.int64(222816),
 'precision_Up': np.float64(1.0),
 'recall_Up': np.float64(2.7214587018641992e-05),
 'f1_Up': np.float64(5.442769281010178e-05),
 'support_Up': np.int64(36745),
 'precision_macro': 0.7067294946088613,
 'recall_macro': 0.3678780445329985,
 'f1_macro': 0.34937758235013466,
 'precision_weighted': 0.7540183631282887,
 'recall_weighted': 0.7580732510652501,
 'f1_weighted': 0.6784610477541858,
 'precision_updown': np.float64(0.6720654396728016),
 'recall_updown': np.float64(0.06182308073027472),
 'f1_updown': np.float64(0.11323015629158224),
 'directional_accuracy': 0.059454342512398096

In [3]:


# from Data_Pipeline.preprocessors.lob_data_process import process_lob_data
# from Data_Pipeline.preprocessors.trade_data_process import process_trade_data
# lob_data_dir = '/root/autodl-tmp/ETHUSDT/20levels_parquet'
# trade_data_dir = '/root/autodl-tmp/ETHUSDT/trade'


# date = [
#         '2025-12-08','2025-12-09','2025-12-10'
#         ]
# levels = 10
# lob_data = process_lob_data(data_dir=lob_data_dir,date = date,levels=levels)
# trade_data = process_trade_data(data_dir=trade_data_dir,date = date,window_ms=100)





In [4]:
# from Data_Pipeline.preprocessors.trade_data_process import align_trade_with_lob
# from Data_Pipeline.preprocessors.lob_data_process import generate_channel_data
# from Data_Pipeline.generators.label_gen import generate_ret_labels

# k= 3000
# lob_data = lob_data.with_columns(
#     pl.col('time_bucket'),
# ((pl.col('a1') + pl.col('a2')) / 2).alias('mid_price'))
# lob_data = generate_ret_labels(lob_data,k=k,mode='smooth',change_window=None)
# ### lobdata 对齐labels
# lob_data = lob_data.drop_nulls(subset=['mid_price_return'])
# labels_ret = lob_data.select(
#     pl.col('mid_price_return')
# ).to_numpy().flatten()
# ### trade 对齐lob
# trade_data = align_trade_with_lob(trade_data = trade_data,full_lob_data = lob_data)
# ## 转为numpy
# # lob_data = lob_data.to_numpy()
# trade_data = trade_data.drop('time_bucket').to_numpy()
# ### 生成channel数据
# lob_data = generate_channel_data(lob_data,levels = levels)
# data_dict = {
#     'lob':lob_data,
#     'trade':trade_data
# }




In [5]:
# import os
# os.makedirs('/root/autodl-tmp/test_data',exist_ok=True)
# np.save('/root/autodl-tmp/test_data/lob_data.npy',lob_data)
# np.save('/root/autodl-tmp/test_data/labels_ret.npy',labels_ret)

In [6]:
lob_data =np.load('/root/autodl-tmp/test_data/lob_data.npy')
trade_data = np.load('/root/autodl-tmp/test_data/trade_data.npy')
labels_ret = np.load('/root/autodl-tmp/test_data/labels_ret.npy')




print(f"trade_data_agg.shape: {trade_data.shape}")
print(f"lob_data.shape: {lob_data.shape}")
print(f"labels_ret.shape: {labels_ret.shape}")

alpha= 0.001
labels_class = np.ones_like(labels_ret, dtype=np.int8)
# 3. 向量化赋值：涨→2，跌→0
# 涨：labels_ret > alpha
labels_class[labels_ret > alpha] = 2
# 跌：labels_ret < -alpha
labels_class[labels_ret < -alpha] = 0

trade_data_agg.shape: (2586002, 12)
lob_data.shape: (2586002, 4, 10)
labels_ret.shape: (2586002,)


In [7]:
np.unique(labels_class,return_counts=True)[1] / np.unique(labels_class,return_counts=True)[1].sum()

array([0.19184324, 0.5974802 , 0.21067656])

In [8]:

## 创建数据集
from Data_Pipeline.dataset import create_dataloaders_for_test
device = 'cuda' if torch.cuda.is_available() else 'cpu'
data_dict = {
    'lob':lob_data,
    'trade':trade_data
}
test_config = {
    'history_T': 3000,
    'batch_size': 512,
    'num_workers': 4,
    'pin_memory': True,
    'stride': 10
}
 # 创建 DataLoader
print("创建 DataLoader...")
test_loader = create_dataloaders_for_test(
    data_dict=data_dict,
    labels=labels_class,
    returns=labels_ret,
    config=test_config,
    device=device
)

print(f"测试集大小: {len(test_loader.dataset)}")


创建 DataLoader...
测试集大小: 258301


In [9]:
print("加载配置...")
from Utils.config_loader import load_config, merge_configs
model_config_path = f'/root/lio/Trade_LOB_MultiModal/checkpoints/{model_version}/model_config.yaml'
train_config_path = f'/root/lio/Trade_LOB_MultiModal/checkpoints/{model_version}/train_config.yaml'
model_config = load_config(model_config_path)
train_config = load_config(train_config_path)


加载配置...


In [10]:
import torch
from pathlib import Path
from typing import Dict, Optional
from Model import MultiModalTransformer # 替换为你的模型文件路径
def load_model_for_inference(
    checkpoint_path: str,
    model_config: dict,
    device: torch.device = None
) -> MultiModalTransformer:
    """
    最终修复版：处理_orig_mod前缀 + 过滤多余key + 加载RevIN缓冲区
    """
    # 1. 自动选择设备
    if device is None:
        device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    # 根据数据情况调整配置
    lob_config = model_config.get('lob_encoder', {})
    trade_config = model_config.get('trade_encoder') if 'trade' in data_dict else None
    fusion_config = model_config.get('fusion', {})
    transformer_config = model_config.get('transformer', {})
    output_config = model_config.get('output_head', {})
    # 2. 初始化模型（配置必须和保存时一致！）
    model = MultiModalTransformer(
        lob_config=lob_config,
        trade_config=trade_config,
        fusion_config=fusion_config,
        transformer_config=transformer_config,
        output_config=output_config,
        use_revin=model_config.get("use_revin", True)
    )
    model = model.to(device)
    # model._init_fusion()
    # 3. 加载checkpoint
    checkpoint = torch.load(
        checkpoint_path,
        map_location=device,
        weights_only=False
    )
    
    # 4. 步骤1：处理_orig_mod前缀
    state_dict = checkpoint["model_state_dict"]
    new_state_dict = {}
    for key, value in state_dict.items():
        if key.startswith("_orig_mod."):
            new_key = key.replace("_orig_mod.", "")
        else:
            new_key = key
        new_state_dict[new_key] = value
    
    # 5. 步骤2：过滤参数key（只保留模型中存在的可训练参数）
    model_param_keys = set(model.state_dict().keys())  # 仅包含可训练参数
    param_state_dict = {}
    buffer_state_dict = {}  # 单独存储缓冲区
    
    for key, value in new_state_dict.items():
        # 区分参数和缓冲区（RevIN的mean/std是buffer，不在model_param_keys中）
        if key in model_param_keys:
            param_state_dict[key] = value
        elif "revin" in key.lower() and (key.endswith("mean") or key.endswith("std")):
            buffer_state_dict[key] = value.to(device)  # 缓冲区转到目标设备
        else:
            print(f"⚠️  过滤多余key：{key}")
    
    # 6. 步骤3：加载可训练参数（strict=True，确保参数100%匹配）
    # 此时param_state_dict只包含模型的可训练参数，无缺失/多余
    model.load_state_dict(param_state_dict, strict=True)
    print(f"✅ 可训练参数加载完成（共{len(param_state_dict)}个）")
    
    # 7. 步骤4：手动加载RevIN缓冲区（关键！保证推理归一化正确）
    if hasattr(model, "trade_revin") and buffer_state_dict:
        # 恢复mean
        if "trade_revin.mean" in buffer_state_dict:
            model.trade_revin.mean = buffer_state_dict["trade_revin.mean"]
            print(f"✅ 恢复RevIN mean: {model.trade_revin.mean.cpu().numpy()}")
        # 恢复std
        if "trade_revin.std" in buffer_state_dict:
            model.trade_revin.std = buffer_state_dict["trade_revin.std"]
            print(f"✅ 恢复RevIN std: {model.trade_revin.std.cpu().numpy()}")
    
    # 8. 切换到推理模式（禁用Dropout/BN/RevIN训练行为）
    model.eval()
    
    print(f"\n🎉 模型加载完成！无任何匹配错误，可直接推理")
    return model

In [15]:
checkpoint_path = f'/root/lio/Trade_LOB_MultiModal/checkpoints/{model_version}/best_model.pt'
import yaml
config_path = f'/root/lio/Trade_LOB_MultiModal/checkpoints/{model_version}/model_config.yaml'
with open(config_path, 'r', encoding='utf-8') as f:
    model_config = yaml.safe_load(f)

In [16]:
model = load_model_for_inference(checkpoint_path,model_config)

✅ 可训练参数加载完成（共65个）
✅ 恢复RevIN mean: [[[5.1229010e+00]
  [1.5509881e-06]
  [1.8308936e-06]
  ...
  [4.2886753e-02]
  [1.1266666e+09]
  [1.7005146e-06]]

 [[5.1166978e+00]
  [1.5698351e-06]
  [1.8900917e-06]
  ...
  [4.2172465e-02]
  [1.1346666e+09]
  [1.7150135e-06]]

 [[5.1143360e+00]
  [1.5809924e-06]
  [1.9054683e-06]
  ...
  [4.1458175e-02]
  [1.1343333e+09]
  [1.7197998e-06]]

 ...

 [[4.8007369e+00]
  [4.5917241e-07]
  [9.1954058e-07]
  ...
  [2.2959728e-03]
  [1.4066668e+09]
  [2.1176238e-06]]

 [[4.7974973e+00]
  [4.5261299e-07]
  [9.1298108e-07]
  ...
  [1.9626401e-03]
  [1.4066666e+09]
  [2.1176236e-06]]

 [[4.8002419e+00]
  [4.2246228e-07]
  [9.0970235e-07]
  ...
  [2.5619643e-03]
  [1.4069999e+09]
  [2.1057824e-06]]]
✅ 恢复RevIN std: [[[2.5267768e+00]
  [3.0103227e-05]
  [3.1016531e-05]
  ...
  [4.1319582e-01]
  [7.7249280e+09]
  [1.7795612e-05]]

 [[2.5317230e+00]
  [3.0123614e-05]
  [3.0999799e-05]
  ...
  [4.1408363e-01]
  [7.7444506e+09]
  [1.7840437e-05]]

 [[2.5333884e+00]

In [17]:
from Train.trainer import Trainer
from Train.train_utils import (
    setup_optimizer,
    setup_scheduler,
    setup_loss_functions,
    set_seed
)
# 设置优化器和调度器
optimizer = setup_optimizer(model, train_config.get('optimizer', {}))
scheduler = setup_scheduler(optimizer, train_config.get('scheduler', {}))

# 设置损失函数
loss_fn = setup_loss_functions(train_config.get('loss', {}), device=device)

# 创建训练器
trainer = Trainer(
    model=model,
    train_loader=None,
    val_loader=test_loader,
    loss_fn=loss_fn,
    optimizer=optimizer,
    scheduler=scheduler,
    config=train_config,
    device=device
)

# 开始训练
print("=" * 50)
metrics = trainer.validate()



print(f"\n{'='*70}")
print("测试集评估结果:")
print(f"{'='*70}")
print(f"  准确率 (Accuracy):  {metrics['accuracy']:.4f}")
print(f"  精确率 (Precision): {metrics['precision_macro']:.4f}")
print(f"  召回率 (Recall):    {metrics['recall_macro']:.4f}")
print(f"  F1分数 (F1-Score):  {metrics['f1_macro']:.4f}")

print(f"\n混淆矩阵:")
print(metrics['confusion_matrix'])
print(f"{'='*70}\n")


Validation:   0%|          | 0/505 [00:00<?, ?it/s]


测试集评估结果:
  准确率 (Accuracy):  0.6916
  精确率 (Precision): 0.6532
  召回率 (Recall):    0.6046
  F1分数 (F1-Score):  0.6234

混淆矩阵:
[[ 24120  22994   2297]
 [ 14118 127176  13117]
 [  2461  24673  27345]]



In [19]:
metrics

{'accuracy': 0.6916001099492453,
 'precision_Down': np.float64(0.5926435538956731),
 'recall_Down': np.float64(0.488150411851612),
 'f1_Down': np.float64(0.5353456886028187),
 'support_Down': np.int64(49411),
 'precision_Stationary': np.float64(0.7273725570940787),
 'recall_Stationary': np.float64(0.8236200788803907),
 'f1_Stationary': np.float64(0.7725099770997467),
 'support_Stationary': np.int64(154411),
 'precision_Up': np.float64(0.6395144881779274),
 'recall_Up': np.float64(0.5019365260008444),
 'f1_Up': np.float64(0.562434439211008),
 'support_Up': np.int64(54479),
 'precision_macro': 0.6531768663892265,
 'recall_macro': 0.6045690055776157,
 'f1_macro': 0.6234300349711912,
 'precision_weighted': 0.6830695365346561,
 'recall_weighted': 0.6916001099492453,
 'f1_weighted': 0.6828346375247457,
 'accuracy_updown': 0.4953797285590528,
 'precision_updown': np.float64(0.6160790210368003),
 'recall_updown': np.float64(0.4950434689262282),
 'f1_updown': np.float64(0.5489689902989552),
 'l

In [15]:
## 保存为pickle文件
import pickle

# 保存为pickle文件
with open(f'/root/lio/Trade_LOB_MultiModal/checkpoints/{model_version}/metrics.pkl', 'wb') as f:
    pickle.dump(metrics, f)



In [23]:
## final
metrics

{'accuracy': 0.6981196356189098,
 'precision_Down': np.float64(0.6268330449039075),
 'recall_Down': np.float64(0.41784218089089475),
 'f1_Down': np.float64(0.5014329431194443),
 'support_Down': np.int64(49411),
 'precision_Stationary': np.float64(0.7127318785128111),
 'recall_Stationary': np.float64(0.874626807675619),
 'f1_Stationary': np.float64(0.7854235001279457),
 'support_Stationary': np.int64(154411),
 'precision_Up': np.float64(0.6863903676245158),
 'recall_Up': np.float64(0.45204574239615264),
 'f1_Up': np.float64(0.5450983864184687),
 'support_Up': np.int64(54479),
 'precision_macro': 0.6753184303470782,
 'recall_macro': 0.5815049103208888,
 'f1_macro': 0.6106516098886196,
 'precision_weighted': 0.6907443274033188,
 'recall_weighted': 0.6981196356189098,
 'f1_weighted': 0.6804106303282713,
 'accuracy_updown': 0.4357782269708345,
 'precision_updown': np.float64(0.6566117062642116),
 'recall_updown': np.float64(0.43494396164352367),
 'f1_updown': np.float64(0.5232702374794679),